global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: scrapper
    static_configs:
      - targets:
          - 192.168.56.1:8081
  - job_name: bot
    static_configs:
      - targets:
          - 192.168.56.1:8091
