app:
  scheduler:
    enable: false
    interval: 15s
    force-check-delay: 15s
  database-access-type: jdbc
  allowedUrlPatterns:
    - https://github.com/(?<owner>.+)/(?<repo>.+)
    - https://stackoverflow.com/questions/(\d+).*

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5437/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  github:
    token: ${GITHUB_TOKEN:}
  stackoverflow:
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN:}
    key: ${STACKOVERFLOW_KEY:}

retry-config:
  retries:
    - client: bot
      type: exponential
      max-attempts: 5
      step: 2
      delay: 2s
      codes:
        - 500
    - client: github
      type: exponential
      max-attempts: 5
      step: 2
      delay: 2s
      codes:
        - 500
    - client: stackoverflow
      type: exponential
      max-attempts: 5
      step: 2
      delay: 2s
      codes:
        - 500
