app:
  telegram-token: ${BOT_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml


springdoc:
  swagger-ui:
    path: /swagger-ui

retry-config:
  retries:
    - client: scrapper
      type: fixed
      max-attempts: 1
      step: 2
      delay: 2s
      codes:
        - 500
